greencommons/commons

- Gemfile
- Gemfile.lock
- app/models/group.rb
- app/models/list.rb
- app/models/resource.rb
- app/models/user.rb
- config/initializers/acts_as_taggable_on.rb
- db/migrate/20161022021345_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
- db/migrate/20161022021346_add_missing_unique_indices.acts_as_taggable_on_engine.rb
- db/migrate/20161022021347_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
- db/migrate/20161022021348_add_missing_taggable_index.acts_as_taggable_on_engine.rb
- db/migrate/20161022021349_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
- db/migrate/20161022021350_add_missing_indexes.acts_as_taggable_on_engine.rb
- db/schema.rb
- db/seeds.rb
Added tagging support using the [`acts_as_taggable_on`](https://github.com/mbleigh/acts-as-taggable-on) gem. Enabled tagging for `User`, `Resource`, `List`, and `Group`.
> Add tag support

- config/database.yml
* Usernames are not required for postgres databases, particularly in development.
* Also: I never set a `root` user for for my development/test databases since it's not necessary.
* Also YAML doesn't support overriding when inheriting, because it's basically just merging hashes.
Changes
=======
* Remove the `root` database username from the default configuration.
* Add it to the `production` group.
Recommended Reviewers
=====================
@ptrikutam
> Don't set a default username in the db

- Rakefile
- circle.yml
* The Heroku deploy step was breaking because the `rubocop` library is not in the `production` gem group.
* The options here are to make Rubocop run when we deploy (seems bad) or only run `rake rubocop` on default when we are in the test environment, which includes CI.
Changes
=======
* Set only `spec` as the default Raketask.
* Add `rubocop` to the default Raketask if we are in the `test` Rails environment only.
Minor
=====
* Use [the preferred Rake task format][1]
* Tell CI to run all RSpec tests, not just those in the `spec` directory. This is not critical now (all specs are in `/spec`) but it is unnecessarily specific and could cause problems later.
[1]: http://po-ru.com/diary/adding-to-the-default-rake-task/
> Limit running rubocop to the test environment

- lib/tasks/rubocop.rake
* Heroku still breaking with this error:
```
remote: sh: 2: Syntax error: Unterminated quoted string
```
* This feels like an environment variable issue but I wanted to isolate it so I'm going to try this first.
* Could be something with trying to load the `rubocop.rake` task under production...
Changes
=======
* Gate the rake task to only `:test`, just like the default bit.
> Limit the rubocop rake task to test only

- db/seeds.rb
- `seeds.rb` is broken:
```
$ heroku run 'rake db:seed' -a greencommons
Running rake db:seed on ⬢ greencommons... up, run.3231 (Hobby)
D, [2016-11-04T23:57:28.504146 #3] DEBUG -- :   ActiveRecord::SchemaMigration Load (1.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
rake aborted!
NameError: undefined local variable or method `n' for main:Object
/app/db/seeds.rb:18:in `block in <top (required)>'
/app/db/seeds.rb:16:in `times'
```
- Added the `n` variable back into the script.
> Fix db seeds script

- bin/setup
- config/initializers/elasticsearch.rb
* Elastic Search is now a hard dependency of this application.
* As such, we should help the user install it, if they haven't done so already.
* https://github.com/greencommons/commons/issues/30
Changes
=======
* Add a step to check for an `elasticsearch` binary, install if it doesn't exist.
* Instead of aborting when some tools are not installed, install them for the user.
Minor
=====
* Avoid echoing to the shell by piping to `/dev/null`.
* Capitalize comments.
> Add elasticsearch installation to setup script

- Procfile.dev
- README.md
* In development, we will need elasticsearch to be running for the app to function and tests to pass.
* https://github.com/greencommons/commons/issues/24
Changes
=======
* Add a line to the `Procfile.dev` to run elasticsearch.
Minor
-----
* Split long line in the initializer.
> Add elasticsearch to the Procfile.dev

- .bummr-build.sh
- Gemfile
- Gemfile.lock
- README.md
* Gems should stay updated.
* Sometimes, they break the app.
* [`bummr`][1] helps us update the gems and figure out which ones break the app.
[1]: https://github.com/lpender/bummr
Changes
=======
* Add the gem
* Add a `.bummr-build.sh` file, which is how it knows how to run the tests.
* Describe the change in the `README.md`.
> Add a bummr for more easily updating gems

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/jobs/indexer_job.rb
- app/models/resource.rb
- app/service/search_index.rb
- spec/factories/lists.rb
- spec/jobs/indexer_job_spec.rb
- spec/models/group_spec.rb
- spec/models/list_spec.rb
- spec/models/resource_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/service/search_index_spec.rb
- spec/spec_helper.rb
* When we perform CRUD actions on an AR model, we want to subsequently update the search index to keep everything in sync.
* That can delay the request cycle, so we should perform those activities in the background.
Changes
=======
* Add custom callbacks instead of the stock ElasticSearch ones.
* Send modified records to a `SearchIndex` service class to abstract away everything about ElasticSearch. Let it enqueue jobs or whatever it wants.
* Create a general job class to add/remove records from the search index. Built it to allow for any type of AR record with `ElasticSearch::Model` mixed in.
* Add `sidekiq` gem for background job processing.
* Add a way to disable the callbacks via `ENV`.
Minor
=====
* Add [`climate_control`] gem for temporarily …
> Run Search Index actions asynchronously

- .rubocop.yml
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/search_controller.rb
- app/jobs/indexer_job.rb
- app/views/layouts/application.html.erb
- app/views/search/new.html.slim
- app/views/static_pages/index.html.erb
- config/routes.rb
- config/sidekiq.yml
- db/migrate/20161130200617_change_resource_metadata_to_required.rb
- db/schema.rb
- spec/feature/user_searches_resources_spec.rb
* We want to set up basic search functionality across Rails/Elasticsearch.
* Also, we'd like to establish one happy-path integration test to ensure the main functionality of the page is working.
Changes
=======
* Add documentation for setting up QT and XCode.
* Add capybara-webkit gem for a headless web driver to simulate rendering a full page.
Minor
=====
* Remove whitespace.
* Add `slim` gem for alternative templating.
* Delete placeholder static page.
* Reduce concurrency to keep up with database connection pool.
* Add logging for debugging
* Allow for up to 3 expectations in one test block.
* Remove duplicate `rspec-rubocop` configuration.
https://trello.com/c/f0lpURT0/27-add-a-search-field-and-return-a-result
> Add Simple Search Results

- .gitignore
- .rubocop.yml
- Gemfile
- Gemfile.lock
- Procfile
- Procfile.dev
- README.md
- app/controllers/search_controller.rb
- app/jobs/indexer_job.rb
- app/service/search_index.rb
- app/views/layouts/application.html.erb
- app/views/search/new.html.slim
- app/views/static_pages/index.html.erb
- config/initializers/sidekiq.rb
- config/routes.rb
- config/sidekiq.yml
- db/migrate/20161130200617_change_resource_metadata_to_required.rb
- db/schema.rb
- spec/feature/user_searches_resources_spec.rb
- spec/service/search_index_spec.rb
* Sidekiq jobs were not working correctly in development for a few reasons:
1. The interface for `IndexerJob` was not being used correctly.
1. There was no `worker` line in the `Procfiles`, so no workers were initiated. Hence, no jobs were being done.
1. Sidekiq was not initialized to use the correct redis connection URL.
Changes
=======
* Add configuration files and initializer for sidekiq for correct functioning.
* Add worker directives to foreman's `Procfile` manifest.
* Correct an interface error when creating `IndexerJob`s.
Minor
-----
* The "hey you've disabled the Elasticsearch callbacks" warning was inverted and incorrect. Fixed here.
* Add the sidekiq web monitoring page at `/sidekiq`, but only in development. …
> Correct Sidekiq configuration

- Gemfile
* Heroku was trying to build the `capybara-webkit` gem and failing.
* It should not be used on production, this was a mistake.
Changes
=======
* Move `capybara-webkit` gem to the test group.
> Move capybara-webkit gem to test environment

- app/helpers/devise_helper.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_alerts.html.erb
Our auth pages look terrible.
- Using the devise generator, generate pages for the login and sign up pages
- Style them with Bootstrap form elements
- Add `shared/_alerts.html.erb` to nicely style alerts from the system in a bootstrap way (and remove the previous alert display code)
- Add `DeviseHelper` to help style devise errors in a bootstrap way
> Style Auth Pages

- config/routes.rb
- config/sidekiq.yml
See #52. Sidekiq (and therefore, all indexing) is currently broken on production. We were [getting an error](https://gist.github.com/ptrikutam/dae56de24d756d36c5f18211117fe7c7) about a maximum number of clients reached for our worker process.
This is because the max number of connections for the Heroku Redis plan we're on is 20. According to [this comment](https://github.com/mperham/sidekiq/issues/117#issuecomment-5027680), the number of connections Sidekiq uses is concurrency + 2. We were over the limit by 2. This PR should reduce the concurrency, and allow us to change it as we like without having to make commits in the future.
- For the sake of debugging, I'm changing `routes.rb` to see Sidekiq's web UI if we set an environment variable. This should be disabled most of the time and …
> Fix Sidekiq

- README.md
- lib/tasks/elasticsearch.rake
There are many times we want to clear the index for ElasticSearch & start over. We want to create a utility task for this.
- add `elasticsearch.rake` with the task to delete the "resources" index
> Add elasticsearch resource index deletion task

- app/controllers/search_controller.rb
- app/views/search/new.html.slim
- spec/feature/user_searches_resources_spec.rb
The search page could use a little visual enhancing.
- Update `SearchController` to not search the Resource index unless there is a query parameter present.
- Update the search field & search results page to be a bit more bootstrap-y. These are by no means final styles but might look a little nicer for proof-of-concepts.
- Before: https://cl.ly/1l44212n1n2C
- After: https://cl.ly/3e3F3K3y2p0H
> Add styles to search page

- app/models/resource.rb
- app/service/search_index.rb
- spec/models/resource_spec.rb
- spec/service/search_index_spec.rb
- spec/spec_helper.rb
* See comment at https://github.com/greencommons/commons/pull/71#discussion_r91873393 :
> Would it make sense to have `RemoveFromIndexJob` directly here instead of having the path go `SearchIndex` -> `RemoveFromIndexJob` -> `SearchIndex`?
Yes.
Changes
=======
* Call the job enqueuing directly from the ActiveRecord model.
* Make the callback flag check and logging class-level methods.
* BUG: Correct index-name configuration error.
Minor
-----
* Set an RSpec file for storing metadata on the last suite run. This is useful for running flags like `--last-failure`.
> Reduce logical complexity for search index jobs

- lib/etl/load/create_new_resource_record.rb
* We don't want to duplicate records in the db when importing epubs.
* There isn't a good way to prevent downloading in the first place, unless we store the AWS S3 bucket/key in our db. This solution would depend on not renaming the files in the S3 bucket or moving them.
Changes
=======
* Only create the record if one does not already exist.
> ETL: Don't create duplicate records

- db/seeds.rb
[Related issue: #80](https://github.com/greencommons/commons/issues/80)
This pull request comes with a new version of the `seed.rb` file, using `FactoryGirl` to create the records. 
It follows the structure presented below:
- Create multiple users with 1 - 2 lists (use a random sampling of 10 - 50 resources for each).
- Create multiple groups with multiple users.
- For each group, create 3 - 5 lists (with a random sampling of 30 - 80 resources for each list)
> Update seeds with FactoryGirl

- Gemfile
Currently getting `NameError: uninitialized constant Kiba` when trying to run the epub import task on Heroku.
Moving it out of the `development` group should do the trick.
> Take Kiba out of development group

- Gemfile
In the last PR, I missed the `epub-parser` gem that's also required to run the ERL process. In this PR, I move this gem out of the `development` group to make it available on Heroku. I did a run in production mode in local and everything seems fine now.
> Move epub-parser out of the development group

- Gemfile
Needed for the ETL process run in production. In the load step, `ap` is used to print some information about the progress. That's why we need to move it out of the `development` group.
> Move awesome-print out of development group

- config/sidekiq.yml
There seems to be a typo in the `sidekiq.yml` file where a single pipe was used instead of the double pipe (OR). In order to have Sidekiq run correctly on Heroku, we need to fix it.
> Change single pipe operator to double pipe in sidekiq config

- lib/tasks/elasticsearch.rake
[Related Issue: ElasticSearch Rake task fails #81](https://github.com/greencommons/commons/issues/81)
To avoid random failures of the `reset_resource_index` task, we need to add `:resource` in its definition.
> Add :environment to the elastic search reset index task

- app/views/devise/sessions/new.html.slim
- spec/feature/user_authenticates_spec.rb
[Related Issue: #74](https://github.com/greencommons/commons/issues/74) and [#53](https://github.com/greencommons/commons/issues/53).
This is a preliminary PR for issue #74. Since users must be logged in to manage groups, I thought it would be nice to have some happy path acceptance tests for the login/logout. I know Devise is handling it, but it's always nice to ensure that we won't have a regression one day by messing with the login form for example.
Implementing this also led me to wonder if we want to stub the logged in user in the acceptance tests for the groups management (faster), or if we should run the user through the login page every time (slower). I like the latter more, since it acts more like a real user, but I'm worried about the speed cost.
PS: These tests pointed out that …
> Add feature test for Authentication

- app/service/search_index.rb
- lib/etl/load/create_new_resource_record.rb
- lib/tasks/elasticsearch.rake
- spec/service/search_index_spec.rb
Related Issues: #57, #96, #97 
This Pull Request changes the way the `index_name` is generated. The method now expects a class such as `Resource` to be passed.
I also removed some `rubocop:disable` that were being reported as unecessary - I'm not getting the warnings anymore.
Finally, I updated the `reset_resource_index` to include an existence check before trying to delete the index (in case it was renamed, not created yet, etc.).
Once this is live, I will reset everything in production (Database + ElasticSearch) and try to import resources from S3.
> Fix the index_name generation for Resource

- lib/etl/extract/process_all_files_in_s3_bucket.rb
- lib/etl/load/create_new_resource_record.rb
- lib/etl/transform/transform_epub.rb
In order to fix #102, we need to know exactly which epub is failing in order to reproduce the bug in local and fix it. This PR includes a few prints in the ETL steps that will tell us which epub is being processed.
> Add simple traces in ETL steps

- lib/etl/load/create_new_resource_record.rb
Related to #102. 
This pull request adds a simple return statement if the `CreateNewResourceRecord` class receives anything but a hash in the `attributes` parameter.
> Skip epub creation when attributes are not a hash

- Gemfile
Related to #87.
To generate some sample data, I'd like to reuse the code created in the `seeds.rb` file (just copy/paste in the console) and to do this, we need Factory Girl available in production. Also, this will help if we ever need to run the seeds in an environment other than development (staging for example).
> Move FactoryGirl out of test/development environments

- .rubocop.yml
- app/models/concerns/indexable.rb
- app/models/group.rb
- app/models/list.rb
- app/models/resource.rb
- lib/tasks/elasticsearch.rake
- spec/models/group_spec.rb
- spec/models/list_spec.rb
- spec/models/resource_spec.rb
- spec/support/shared/indexable.rb
Related issue: #98 
> Taking the search term entered and searching across Group, Resource, and List to begin with. The search page should return a list of all items combined together.
This pull request turns `Group` and `List` into models indexed with ElasticSearch. The logic was extracted from the `Resource` model and moved into a concern (`Indexable`) for easy reuse. 
New rake tasks were also added to reset/create the indices for the new models (with a fallback if the `Model.import` method fails). 
Finally, the tests checking if a model is correctly indexed on `create` / `delete` were moved into a shared example and included in each of the models mentioned above.
> Setup ES indices for Groups and Lists

- lib/tasks/rubocop.rake
Currently, when running `bundle exec rake` (which runs `rspec` and the `rubocop` rake task), we are getting offenses that should be ignored by the configuration defined in [.rubocop.yml](https://github.com/greencommons/commons/blob/fix-rubocop-rake-task/.rubocop.yml).
Changing this rake task to use `RuboCop::RakeTask.new` seems to fix the issue.
> Change Rubocop rake task to use .rubocop config

- .rubocop.yml
- Gemfile.lock
- app/jobs/update_index_job.rb
- app/models/concerns/indexable.rb
- app/service/search_index.rb
- app/views/search/new.html.slim
- spec/feature/user_searches_resources_spec.rb
- spec/service/search_index_spec.rb
Related Issues: #108, #43 and #44 
This pull request adds a new indexing process for existing records. Instead of re-indexing entire documents every time an update is made, it will select the changed fields and send them Elastic Search. In case the record wasn't indexed for some reason, it will perform a full indexing.
I also made the remove process more robust by failing silently if the record wasn't indexed (using the same mechanism as the update: by rescuing from `Elasticsearch::Transport::Transport::Errors::NotFound`.
> Implement ES update mechanism

- app/assets/javascripts/components/autocomplete_form.js.jsx
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_top-page-form.scss
- app/controllers/search_controller.rb
- app/helpers/summary_cards_helper.rb
- app/views/members/index.html.slim
- app/views/search/new.html.slim
- app/views/search/show.html.slim
- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_list.html.slim
- app/views/shared/summary_cards/_main.html.slim
- app/views/shared/summary_cards/_resource.html.slim
- config/routes.rb
- spec/feature/user_manages_groups_spec.rb
- spec/feature/user_searches_resources_spec.rb
- spec/rails_helper.rb
Related issue: #98 (Points 1 and 2)
This pull request adds a simple search result page, stripped down from any complexity that will be added in future pull requests. There are many small changes on the front-end side, which made sense to make this PR stands on its own.
The ElasticSearch score was added for each record, I don't think this will be the final value being shown but it's a start. There is no filtering, no sorting and no pagination for now.
I'm also wondering if we should add [Font Awesome](http://fontawesome.io/) to the project to replace the very limited amount of icons coming with Bootstrap.
> Implement basic search page

- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_resource.html.slim
The titles in the summary cards should link to the corresponding record page.
> Make titles in summary cards link to the record

- app/helpers/score_helper.rb
- app/views/shared/components/_score.html.slim
- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_list.html.slim
- app/views/shared/summary_cards/_resource.html.slim
This pull request improves the way the score is displayed in the search results. It is now using colored labels depending on the value:
- `score > 1` :  Green
- `score > 0.5` : Orange
- `score > 0` : Red
I tried to change the scores to be percent but wasn't able to. I thought the returned score was only between 0 and 1, which would have been easy to translate to percent. However, ES can return higher score values and doesn't seem to have a maximum. The second option I thought about was to use the top score as 100% but this seems not to be encouraged based on what I read [here](http://stackoverflow.com/questions/3986220/how-do-i-normalise-a-solr-lucene-score). I wasn't able to find any more examples than this about switching to percent and left it to ES score for now, with a `round(3)` to …
> Show score as colored label

- config/initializers/assets.rb
We are getting 500 errors on Resource vie pages (https://greencommons.herokuapp.com/resources/7577). 
```
2017-02-03T19:44:54.052037+00:00 app[web.1]: F, [2017-02-03T19:44:54.051984 #6] FATAL -- : [8804aaad-665b-46cf-8d87-bf6c7b319098] ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
2017-02-03T19:44:54.052275+00:00 app[web.1]: F, [2017-02-03T19:44:54.052205 #6] FATAL -- : [8804aaad-665b-46cf-8d87-bf6c7b319098]     20:
2017-02-03T19:44:54.052348+00:00 app[web.1]: F, [2017-02-03T19:44:54.052296 #6] FATAL -- : [8804aaad-665b-46cf-8d87-bf6c7b319098]     21:   .row.page-details__row
2017-02-03T19:44:54.052461+00:00 app[web.1]: F, [2017-02-03T19:44:54.052369 #6] FATAL -- : [8804aaad-665b-46cf-8d87-bf6c7b319098]     22:     .col-xs-12 …
```
> Precompile React

- .rubocop.yml
- app/assets/javascripts/components/tags.jsx
- app/controllers/resources_controller.rb
- app/controllers/search_controller.rb
- app/controllers/tags_controller.rb
- app/models/concerns/indexable.rb
- app/models/concerns/taggable.rb
- app/models/group.rb
- app/models/list.rb
- app/models/resource.rb
- app/service/suggesters/tags.rb
- app/services/suggesters/tags.rb
- app/views/groups/show.html.slim
- app/views/resources/show.html.slim
- app/views/search/show.html.slim
- app/views/shared/components/_explore.html.slim
- app/views/shared/components/_tags_list.html.slim
- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_resource.html.slim
- config/initializers/acts_as_taggable_on.rb
- db/migrate/20170203021400_add_cached_tag_list_to_groups.rb
- db/migrate/20170203021406_add_cached_tag_list_to_resources.rb
- db/migrate/20170204041142_add_cached_tags_to_lists.rb
- db/schema.rb
- spec/feature/user_interacts_with_resources_spec.rb
- spec/feature/user_searches_resources_spec.rb
- spec/rails_helper.rb
- spec/services/suggesters/tags_spec.rb
Issue: #98 & #99 
Depends on PR #118 for tags and PR #117 for the correct version of ES in CircleCI (hence the failing tests).
This pull request adds the __Explore__ section to resources and the __You may also like__ section containing up to 6 suggestions based on the records tags.
I had quite a few issues with ES indexing since the tags are store in external tables. At first, I tried using the caching system from `acts-as-taggable-on` but it was so damn buggy that I switch to a custom and simple one. 
- All the tags of the searched records are now used to find related records
- Clicking on a tag will take you to the search page with that tag as the query
- Feature specs for related records on search and resource pages
- Use of `cached_tags` everywhere to speed things up and prevent tons …
> Suggestions for search and resource based on tags

- app/views/groups/index.html.slim
- app/views/groups/show.html.slim
- app/views/members/index.html.slim
- app/views/shared/components/_explore.html.slim
Related Issue: #122 
This pull request fixes the alignment issue we were having when displaying records two by two. To prevent the issue, we are now using `each_slice(2)` and adding the `.row` class for each line.
> Fix alignment issues when showing records 2 by 2

- app/controllers/search_controller.rb
- app/views/search/show.html.slim
Related issue: #127 
This pull request fixes the displayed total number of results for a search. Until now, it was showing the count after pagination and made little sense. It should now be using the total number of records found in ES.
> Fix Total Search Count

- app/services/search_builders/query.rb
Related Issue: #128 
This pull request adds two fields to the ones being searched by ES when making a search on the website: `content` and `long_description`.
I will wait for an answer to my question on the issue so see if I should change the `match` queries to `match_phrase`.
> Add content and long_description to the fields searched by ES

- app/models/concerns/indexable.rb
- app/services/search_builders/sorter.rb
- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_list.html.slim
- app/views/shared/summary_cards/_resource.html.slim
- db/migrate/20170217083000_add_published_at_to_resources.rb
- db/migrate/20170217083004_add_published_at_to_groups.rb
- db/migrate/20170217083008_add_published_at_to_lists.rb
- spec/services/search_builders/sorter_spec.rb
- spec/support/shared/indexable.rb
Related Issue: #123 
This pull request creates a shared date field named `published_at` for the `Group`, `Resource` and `List` models. This field is used to sort the records when searching through ElasticSearch. The value is defined when the record is created using either `metadata[date]` or `created_at`.
> Generate published_at date after creation

- app/uploaders/avatar_uploader.rb
- spec/feature/user_updates_profile_spec.rb
There is a bug right now where it looks like a user cannot update his profile picture. This is due to the way the avatar filename is saved - since there is no stamping, the browser is caching the picture and won't get the new one because they have the same name.
- Change the `filename` method using [this](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Use-a-timestamp-in-file-names) as an example.
> Add time stamping to user avatars

- app/helpers/link_helper.rb
- app/views/shared/summary_cards/_resource.html.slim
- spec/feature/user_manages_resources_spec.rb
[Trello Task](https://trello.com/c/QSOWiZbm/19-green-commons-link-the-view-original-to-a-hypothesis-via-link)
Until now, the "View Original Document" button present in the summary cards for resources wasn't pointing to anything. Now, if the resource has a URL, it will link to it through Hypothesis.
- Add `via_hypothesis` helper to build final URL.
- Update Resource summary card.
- Add a test to ensure the hypothesis URL is correctly generated.
> Link to Hypothesis when clicking on View Original Document

- app/views/groups/show.html.slim
- app/views/layouts/application.html.slim
- app/views/resources/show.html.slim
- app/views/shared/integrations/_disqus.html.slim
- app/views/shared/integrations/disqus/_comments.html.slim
- app/views/shared/integrations/disqus/_script.html.slim
- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_resource.html.slim
[Trello Task](https://trello.com/c/WQLZUjKt/20-green-commons-add-disqus-to-resource-group-pages)
This pull request adds the Disqus comments system to every resource and group pages. It also includes the comments count in the summary cards for these types of records.
> Add Disqus To Resources and Groups pages

- app/views/resources/show.html.slim
- spec/feature/user_manages_resources_spec.rb
This pull request adds the Hypothesis link to original document on the resource pages.
- Add Hypothesis link if the resource has a URL.
- Update the tests checking the presence or absence of the View Original Document.
> Add Hypothesis link on Resource page

- app/services/search_builders/model_lister.rb
- app/services/search_builders/resource_type_filter.rb
- spec/requests/api/v1/search_controller_spec.rb
- spec/services/search_builders/model_list_spec.rb
- spec/services/search_builders/resource_type_filter_spec.rb
[Trello Task](https://trello.com/c/96kVR3Hx/25-green-commons-search-api-faceting)
This pull request makes it easier to do filtering/faceting for the Search resource. It can be used like this:
```
GET http://localhost:3000/api/v1/search?q=term&filters[model_types]=resources,lists,groups&filters[resource_types]=books,articles,reports
```
> Web API - Filtering/Faceting

- app/controllers/api/v1/search_controller.rb
- spec/requests/api/v1/search_controller_spec.rb
- spec/support/api/schemas/jsonapi.json
[Trello Task](https://trello.com/c/sNh0NW8K/26-green-commons-search-api-you-may-also-like)
This pull request adds the related entities to the search results JSON response. It adds them in the `related` key at the root level of the response. This kind of violates the JSON API specification but I didn't see where else to put them.
> Web API - You May Also Like

- app/controllers/api/api_controller.rb
- lib/yumi/base.rb
- lib/yumi/presenter.rb
- lib/yumi/presenters/attributes.rb
- lib/yumi/utils/presenter_helper.rb
- spec/lib/yumi/presenter_spec.rb
- spec/lib/yumi/presenters/attributes_spec.rb
- spec/requests/api/v1/search_controller_spec.rb
[Trello Task](https://trello.com/c/c6omCM8R/41-green-commons-search-api-field-picking)
Merge after [this PR](https://github.com/greencommons/commons/pull/151) (and after switching the base branch).
This pull request gives the option to users to select which fields they want to get from the Search resource as defined in the [JSON API Specification](http://jsonapi.org/format/#fetching-sparse-fieldsets).
Example: 
```
GET https://localhost:3000/api/v1/search?q=term&fields[groups]=name,long_description
```
> Web API - Field Picking

- app/assets/javascripts/components/autocomplete_form.js.jsx
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_autocomplete.scss
- app/assets/stylesheets/components/_form-box.scss
- app/assets/stylesheets/components/_sidelist.scss
- app/assets/stylesheets/components/_top-page-form.scss
- app/assets/stylesheets/components/_user-picture.scss
- app/assets/stylesheets/helpers/_buttons.scss
- app/assets/stylesheets/pages/_default.scss
- app/assets/stylesheets/pages/_resource.scss
- app/controllers/groups_controller.rb
- app/models/concerns/taggable.rb
- app/models/groups_user.rb
- app/views/groups/_form.html.slim
- app/views/groups/edit.html.slim
- app/views/groups/index.html.slim
- app/views/groups/new.html.slim
- app/views/groups/show.html.slim
- app/views/members/index.html.slim
- app/views/shared/summary_cards/_member.html.slim
- spec/feature/user_interacts_with_groups_spec.rb
- spec/feature/user_manages_groups_spec.rb
Depends on PR #156.
A new design has been created for Green Commons and it was requested to update the current design.
This pull request includes the new design for all group-related pages:
- Group list (my groups)
- Group show page
- Group Create and Edit
- Group members list (custom made because no design, just reused elements from other pages). Can be accessed by clicking the members count on the group page, there didn't seem to be any other button to access it in the design.
> New design for groups pages

- app/assets/javascripts/components/add_to_list/add_to_list_form.js.jsx
- app/assets/javascripts/components/autocomplete_select.js.jsx
- app/assets/javascripts/components/create_list/owner_picker.js.jsx
- app/assets/stylesheets/components/_user-picture.scss
- app/controllers/autocomplete_controller.rb
- app/controllers/lists_controller.rb
- app/helpers/types_helper.rb
- app/models/concerns/indexable.rb
- app/models/group.rb
- app/models/list.rb
- app/models/user.rb
- app/services/suggesters/list_owners.rb
- app/services/suggesters/lists.rb
- app/views/lists/_form.html.slim
- config/routes.rb
- lib/tasks/elasticsearch.rake
- spec/feature/user_manages_lists_spec.rb
- spec/rails_helper.rb
In the current implementation, we load all the groups/users to fill the `select` options. This is not a viable solution on the long term and we need to switch to a remote autocomplete style.
- Set up Users to be indexed in ES.
- Added mappings for the Group model (for ES).
- Replace owner select in List form to be a React component (using `select2`) that will retrieve suggestions from the server when the user starts typing.
If having both groups and users in the same results becomes too annoying (like a user cannot find a user because too many groups match his query), we could add another select above letting the user pick which type of owner he wants to set, and only search for that specific type after that.
> Dynamic owner search for list form

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/components/add_to_list/add_to_list_button.js.jsx
- app/assets/javascripts/components/add_to_list/add_to_list_form.js.jsx
- app/assets/javascripts/components/add_to_list/add_to_list_loading.js.jsx
- app/assets/javascripts/components/add_to_list/add_to_list_modal.js.jsx
- app/assets/javascripts/components/autocomplete_select.js.jsx
- app/assets/javascripts/components/create_list/owner_picker.js.jsx
- app/assets/stylesheets/application.scss
- app/controllers/autocomplete_controller.rb
- app/helpers/types_helper.rb
- app/models/user.rb
- app/policies/list_policy.rb
- app/services/suggesters/lists.rb
- app/views/groups/show.html.slim
- app/views/lists/_form.html.slim
- app/views/resources/show.html.slim
- app/views/shared/summary_cards/_group.html.slim
- app/views/shared/summary_cards/_resource.html.slim
- spec/feature/user_manages_lists_spec.rb
- spec/models/user_spec.rb
- spec/policies/list_policy_spec.rb
- spec/services/suggesters/lists_spec.rb
Currently the dropdown to add a resource to a list doesn't show any list. It would be nice to show 5 lists owned by the current user to make things easier.
- Switch to Selectize from Select2 in order to correctly pre-populate the select
- Allow any user belonging to a group owning a list to edit it
- Change the add to list feature to only allow a user to add to lists he owns or belongs to a group owning them
> Improve Add To List dropdown

- app/controllers/groups_controller.rb
- app/views/shared/summary_cards/_group.html.slim
Currently, the group page isn't displaying the lists owned by the group. Instead, it shows the lists to which a group has been added.
This PR changes the logic to display the lists owned by the group being viewed instead of the lists to which the group belongs.
> Fix lists not showing up correctly on group page

- README.md
- app/controllers/api/api_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/shared/users.rb
- app/controllers/users/profile_controller.rb
- app/policies/user_policy.rb
- config/routes.rb
- spec/requests/api/v1/users_controller_spec.rb
GC requested new resources to be added to the web API.
- Add endpoints to create and update users
I'm not sure how we want to handle file uploads through the API so I haven't implemented anything yet. If we want to stick with the JSON API spec, the files should probably be base64 encoded and sent as part of the JSON. 
There are two other options though:
- Use a different mime-type (like a regular `multipart/form-data`) for endpoints where files can be sent (user creation, resource creation) that can receive both text parameters and files.
- Separate the file creation from the resource creation by creating a separate endpoint that only deals with receiving files and associating with the resources.
> Web API - User Resources

- README.md
- app/controllers/api/api_controller.rb
- app/controllers/api/v1/resources_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/shared/users.rb
- app/controllers/users/profile_controller.rb
- app/policies/user_policy.rb
- app/presenters/v1/resource_presenter.rb
- config/routes.rb
- spec/requests/api/v1/resources_controller_spec.rb
- spec/requests/api/v1/users_controller_spec.rb
GC requested new resources to be added to the web API.
This pull request adds new endpoints for resources:
- View a resource
- Create a resource
- Update a resource
These endpoints work exactly like in the web application, which means resources are created as `private` by default. 
- Should we make it possible for users to change all list attributes through the API and upload files?
- I haven't done anything with tags yet, I'm thinking about just doing it in a common PR for groups/resources/lists. Should a user just be able to send a list of tags and we add them?
> Web API - Resources endpoints

- app/controllers/api/api_controller.rb
- config/application.rb
- lib/middleware/catch_json_parse_errors.rb
- spec/requests/api/v1/networks_controller_spec.rb
Currently, sending a malformed JSON or invalid parameters is returning a 500 error. The server should return 400 instead since the client is sending incorrect requests.
- Catch JSON parsing errors
- Add tests checking that the API is behaving as expected
> Fix 500 API errors (malformed JSON & Invalid params)

- app/controllers/api/api_controller.rb
- app/models/resource.rb
- app/views/shared/summary_cards/_resource.html.slim
- config/application.rb
- db/migrate/20170615070755_remove_content_from_resources.rb
- db/schema.rb
- lib/etl/transform/transform_epub.rb
- lib/middleware/catch_json_parse_errors.rb
- lib/tasks/resources.rake
- spec/factories/resources.rb
- spec/requests/api/v1/networks_controller_spec.rb
Resources now have `short_content` and `long_content` instead of `content` which should be removed.
- Remove `content` from `resources`
- Replace all occurrences of `content` in the code
> Remove content from resources

- lib/etl/load/create_new_resource_record.rb
- spec/etl/local_json_resources_to_db_spec.rb
By default, resources are created as private so all resources uploaded by users will be private by default. This means we need to update the ETL resource load class to set the resources as public.
- Set the privacy of loaded resources to public
- Ensure the loaded resources are set to public correctly
I've started running a script to update the privacy of all the resources that were imported.
> Set resources imported through ETL to public

- app/assets/stylesheets/components/_summary-card.scss
- app/assets/stylesheets/helpers/_buttons.scss
- app/views/shared/summary_cards/_resource.html.slim
Depends on PR #175.
Currently, the summary cards for resources don't show the link to the original URL.
- Add button linking to original URL through hypothesis in resource summary cards.
> Resources that contain URLs should show the "view original" link

- Gemfile
- Gemfile.lock
We're getting a lot of memory errors on Heroku. In order to fix them, we need to figure out what's wrong.
- Add the Scout gem
> Add Scout gem

- app/services/search_builders/query.rb
- app/views/search/_results.html.slim
- app/views/shared/summary_cards/_resource.html.slim
We thought there was something wrong with the indexing of the metadata for resources. After checking it, I realized that the issue was not in the indexing but in the way we search for the resources. In our implementation, we need to specify each field in which we want to search.
I added the metadata publisher, creators and isbn fields and fixed the content/description fields. Let me know if we need to search in more fields.
> Add new fields for search

- app/views/networks/show.html.slim
- app/views/resources/show.html.slim
- app/views/shared/summary_cards/_network.html.slim
- app/views/shared/summary_cards/_resource.html.slim
- spec/feature/user_manages_networks_spec.rb
- spec/feature/user_manages_resources_spec.rb
If no short content is available, we should show the truncated long content.
- Use `short_content` if available, else truncate `long_content`
> Use short/long content appropriately

- app/controllers/api/v1/relationships/items_controller.rb
- app/controllers/list_items_controller.rb
- app/controllers/static_pages_controller.rb
- app/models/lists_item.rb
- app/models/networks_user.rb
- app/presenters/v1/network_presenter.rb
- app/views/lists/_items.html.slim
- app/views/members/index.html.slim
- app/views/networks/show.html.slim
- app/views/resources/show.html.slim
- app/views/shared/summary_cards/_list.html.slim
- app/views/shared/summary_cards/_network.html.slim
- app/views/shared/summary_cards/_resource.html.slim
- app/views/shared/summary_cards/mini/_network.html.slim
- app/views/static_pages/_connect.html.slim
- app/views/static_pages/_content.html.slim
- db/migrate/20170813141720_add_users_count_to_networks.rb
- db/migrate/20170813144526_add_items_count_to_lists.rb
- db/migrate/20170813145314_add_lists_count_to_networks_and_resources.rb
- db/schema.rb
- lib/tasks/counters.rake
Queries for the home and search pages are not currently optimized and using up too much memory on Heroku, causing errors.
- Reduce the number of SQL queries made
- Add counter caches
This does not include view caching, which will be done in a future PR.
> Memory Improvements for home and search pages

- app/views/lists/_form.html.slim
- app/views/lists/edit.html.slim
- app/views/lists/new.html.slim
- app/views/networks/_form.html.slim
- app/views/networks/edit.html.slim
- app/views/networks/new.html.slim
- app/views/resources/_form.html.slim
- app/views/resources/edit.html.slim
- app/views/resources/new.html.slim
Currently, the notice/alert panel is shown inside the form box, but goes out of bounds.
- Move the notice/alert outside of the form box, back at the top of the page like for the other pages.
> Fix alert position in form views

- app/assets/javascripts/filters.js
- app/services/search_builders/builder.rb
- app/services/search_builders/date_filter.rb
- app/services/search_builders/search.rb
- app/views/search/_filters.html.slim
- spec/feature/user_searches_resources_spec.rb
- spec/services/search_builders/date_filter_spec.rb
Date filtering is currently not implemented, this PR adds it.
- Add date filtering
- Add tests to ensure dates can be selected and URLs containing the filters are correctly interpreted by the calendar
> Implement date filtering

- app/helpers/icon_helper.rb
- app/views/lists/show.html.slim
- app/views/resources/show.html.slim
- app/views/shared/components/_content_viewer.html.slim
- app/views/shared/icons/_audio.html.slim
- app/views/shared/icons/_course.html.slim
- app/views/shared/icons/_dataset.html.slim
- app/views/shared/icons/_image.html.slim
- app/views/shared/icons/_profile.html.slim
- app/views/shared/icons/_syllabus.html.slim
- app/views/shared/icons/_url.html.slim
- app/views/shared/icons/_video.html.slim
This pull request contains a few minor changes to the resource page.
- [Remove the content viewer section](https://trello.com/c/c6alismC/112-green-commons-remove-the-content-viewer-section-from-resource-pages)
- [Hide View Original](https://trello.com/c/exvRQcUu/103-green-commons-hide-view-original-when-there-is-no-link)
- [Add icons for all resource types](https://trello.com/c/V0F6X5lk/104-green-commons-profile-icon-is-missing)
- [Change Privacy to License](https://trello.com/c/DxNPaGRq/113-green-commons-resource-page-change-privacy-to-license)
> Fix resource page

- app/services/search_builders/builder.rb
- app/services/search_builders/query.rb
- app/views/search/_filters.html.slim
- app/views/shared/components/_tags_list.html.slim
- app/views/static_pages/_hero.html.slim
- spec/feature/user_searches_resources_spec.rb
- spec/services/search_builders/date_filter_spec.rb
- spec/services/search_builders/query_spec.rb
- spec/services/search_builders/resource_type_filter_spec.rb
[Trello Task](https://trello.com/c/tOUulYpo/114-green-commons-enable-searching-by-tag-only)
Currently, tags are not used in the search process. This needs to be altered in order to have tags as primary matchers.
- Include tags in the search process
- Update the list of tags in the search filters sidebar
> Search by tags

- app/views/search/show.js.erb
- spec/feature/user_searches_resources_spec.rb
rel: #216 
Notes:
- `ReactRailsUJS.unmountComponents()` removes the components that are not rendered anymore. This prevents memory leaks
- `ReactRailsUJS.mountComponents()` forces to mounts the new and existent components.
> #216 - Fix 'Add to List' button display when search filter is applied

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_carousel-indicators.scss
- app/controllers/static_pages_controller.rb
- app/views/static_pages/_connect.html.slim
- app/views/static_pages/home.html.slim
- spec/controllers/static_pages_controller_spec.rb
- spec/factories/resources.rb
- spec/rails_helper.rb
Changes: 
* Last carousel indicator shows the network last card
* The Network displayed now are 10 and are random
* Fixed the display position of the last indicator for small desktop screens.
* Also added a new dependency on testing env: `rails-controller-testing`. It provides the `assigns` helper method.
Notes:
* I moved the Network DB query outside of the view. Reason: Anti pattern.
#189
> Fixed Connect carousel last indicator and network display items changed

- README.md
- lib/tasks/elasticsearch.rake
Related to issue #255 
- Added rake task for create indices on ElasticSearch for Resource, Network, List and User records. 
- Readme.md Updated.
Also I added the proper namespace to the elastic_search reset tasks.
> Issue #255 - Create rake task for create indices in ElasticSearch.

- app/controllers/static_pages_controller.rb
- app/views/shared/components/_resource_details.html.slim
- app/views/static_pages/_content.html.slim
- spec/controllers/static_pages_controller_spec.rb
- spec/factories/resources.rb
- spec/feature/user_visits_home_page_spec.rb
* "See more" links have been replaced by "View all"  
* Arrow icon on "View All" links have been removed
* "View All" link now points to the search page
https://github.com/greencommons/commons/issues/199
> Issue  #199 - Replace links of resources. Goes to the search page

- .eslintrc
- .hound.yml
We'd like to start linting for our ES6 classes.
- add `eslint` linting to hound
- add `.eslintrc` and extend the Airbnb style
> add airbnb eslint

- app/assets/javascripts/filters.js
- app/views/search/_filter.html.slim
- app/views/search/_filters.html.slim
- app/views/search/_form.html.slim
- app/views/search/show.html.slim
- app/views/search/show.js.erb
- app/views/shared/_nav.html.slim
- spec/feature/user_searches_resources_spec.rb
Issue: https://github.com/greencommons/commons/issues/196
When the user wants to search using a new term, the filter selection is reset. 
* The search bar on the nav bar performs new search using all filters
* The search bar on the search page will keep the filter selection
> Issue #196 - Added search bar on search page

- app/helpers/link_helper.rb
- app/views/lists/_form.html.slim
- app/views/networks/_form.html.slim
- app/views/resources/_form.html.slim
- spec/feature/user_manages_lists_spec.rb
- spec/feature/user_manages_networks_spec.rb
- spec/feature/user_manages_resources_spec.rb
- spec/helpers/link_helper_spec.rb
* Resource, Network and List forms have a cancel button
* The cancel button goes to the previous page
* If there is no previous page or the previous page is a form, goes to root page
https://github.com/greencommons/commons/pull/205
> Issue #205 - Implement cancel button for forms

- Gemfile
- Gemfile.lock
- config/initializers/rollbar.rb
Error reporting and management is useful for monitoring failures in production environments.
- gem `rollbar`added
- rollbar configuration file added
> Issue #271 - add rollbar for error reporting.

- API.md
- README.md
- app/views/shared/_home_footer.html.slim
- app/views/static_pages/_connect.html.slim
API documentation, as well as other locations in the code are using the old URL for the website.
- Update all instances of `greencommons.herokuapp.com` to `greencommons.net`
> update all urls from heroku to greencommons.net

- .gitignore
- .ruby-gemset
- Gemfile
- config/environments/production.rb
We're getting an error message on production when trying to send emails: 
```
Errno::ECONNREFUSED (Connection refused - connect(2) for "localhost" port 25):
```
According to [this StackOverflow post](https://stackoverflow.com/questions/17141004/errnoeconnrefused-connection-refused-connect2-for-action-mailer), it appears we haven't set up ActionMailer correctly on production.
- Add a `.ruby-gemset` file for easy gemset selection in RVM
- Add `sendgridy-ruby` gem in the production group
- Set up SMTP options in `production.rb`
> Set up SendGrid
