greencommons/commons

circle.yml
Update the ruby version that is used on CircleCI.
=> Upgrade ruby version

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20161007035503_devise_create_users.rb, db/schema.rb
Generated basic `User` model & simple authentication via the [devise] gem.
[devise]: https://github.com/plataformatec/devise
=> Add User Model & Simple Authentication

app/controllers/application_controller.rb, app/models/user.rb, config/initializers/paper_trail.rb, db/migrate/20161007044258_create_versions.rb, db/schema.rb
The [paper_trail] gem tracks changes to our models' data. Useful, exciting stuff.
[paper_trail]: https://github.com/airblade/paper_trail
=> Add paper_trail for database change tracking & versioning

Gemfile, Gemfile.lock, spec/factories/users.rb, spec/models/user_spec.rb
Basic user specs for the fields we currently have.
=> Add user specs

Gemfile, Gemfile.lock, app/models/group.rb, app/models/user.rb, db/migrate/20161021212448_create_groups.rb, db/schema.rb, spec/factories/groups.rb, spec/models/group_spec.rb, spec/models/user_spec.rb
This PR:
- Creates the Groups table with basic fields (with some super-basic validation)
- Adds the `shoulda` gem for easy association checking
- Adds an association Users & Groups (and relevant specs specs)
=> Add Groups

app/models/resource.rb, db/migrate/20161021221400_create_resources.rb, db/schema.rb, spec/factories/resources.rb, spec/models/resource_spec.rb
This PR:
- Creates the Resource model with basic fields (`title`, `resource_type`, and `metadata`)
- Adds an association to User (and relevant specs)
Notes:
- I'm keeping `resource_type` as an `enum` for now, we can always change that later if we want (with a careful migration).
=> Add resources

app/views/layouts/application.html.erb, app/views/pages/style.html.erb, app/views/shared/_nav.html.erb
We want to have a style guide in place so we know how to use the various markup & components that are present in the application.
- Add a style guide (starting with the base Paper theme from bootswatch) in `/app/views/pages/style.html.erb`
- Add a navigation bar in a partial `app/views/shared/_nav.html.erb` that enables signing in and out of the application.
=> Add style guide and nav bar

app/controllers/groups_controller.rb, app/controllers/members_controller.rb, app/helpers/date_helper.rb, app/models/group.rb, app/models/groups_user.rb, app/views/members/index.html.slim, app/views/shared/summary_cards/_member.html.slim, spec/models/group_spec.rb, spec/requests/groups_controller_spec.rb, spec/requests/members_controller_spec.rb
* We had some Rubocop style failures on master.
Changes
=======
* Fix style issues.
=> Rubocop Fixes

spec/feature/user_searches_resources_spec.rb
Oops. In my excitement to get the PRs merged, I let a few offenses slip through. I fix them in this PR.
Sorry, my mistake. :(
=> Fix Rubocop offenses

README.md
[Trello Task](https://trello.com/c/5v2mAU6S/40-green-commons-add-some-documentation-about-the-search-api)
This pull request adds some documentation about the Search API usage. It still very basic so I only added to the Readme. However, as we move forward, I would recommend setting up some real documentation tool like [Stoplight](https://stoplight.io/) to make it easy for anyone to understand and play with the GC web API. 
Note that some of the documented features are not live yet and are still at the PR step.
PS: I don't know why I ended up with a `checkout` in the branch name, probably mixed things up when I checked out the branch :p
=> Add some documentation about the Search API

app/services/search_builders/resource_type_filter.rb, spec/services/search_builders/resource_type_filter_spec.rb
The faceting is currently buggy and not working as expected.
Add the new supported resource types and fix the search query.
=> Fix Search Faceting

app/assets/stylesheets/components/_feature-box.scss, app/assets/stylesheets/components/_hero-box.scss, app/views/static_pages/_connect.html.slim, app/views/static_pages/_hero.html.slim
The home page still contains Lorem Ipsum content.
- Add the new copy to the home page
- Add description to feature boxes
No content was provided for the subtitle of each feature box (above the title, see screenshot below) so I left it as it was in the design.
=> Update home page copy

app/assets/stylesheets/components/_form-box.scss, app/controllers/static_pages_controller.rb, app/views/shared/_footer.html.slim, app/views/shared/_home_footer.html.slim, app/views/static_pages/about.html.slim, config/routes.rb
This pull request adds the about page as requested by the GC team.
=> Add About page

app/views/shared/summary_cards/mini/_network.html.slim, app/views/static_pages/_connect.html.slim, app/views/static_pages/_content.html.slim, app/views/static_pages/_hero.html.slim
This pull request includes all the tasks related to the home page.
- [Homepage typos](https://trello.com/c/ncInWx5e/106-green-commons-homepage-typos)
- [Homepage randomly select contents](https://trello.com/c/rRdtDa9M/107-green-commons-homepage-randomly-select-content-in-browse-section)
- [Homepage copy edits](https://trello.com/c/hYhsJGno/109-green-commons-homepage-copy-edits)
=> Homepage fixes

app/presenters/v1/resource_presenter.rb
This pull request adds metadata to the resource representations.
=> Add metadata to resources

spec/feature/user_searches_resources_spec.rb
@ptrikutam This PR Fixes the current broken spec.
=> Fix feature spec

app/views/static_pages/_hero.html.slim
This an update for text in Home page, Explore section.
=> Issue 261 update text on home page

app/assets/javascripts/components/add_to_list/add_to_list_confirmation.js.jsx, app/models/lists_item.rb, spec/models/lists_item_spec.rb
Notes:
- This change affects all components that has the button "Add to list".
TODO:
How looks now:
=> #217 - Fix error display when user tries to add the same item to a list

app/controllers/static_pages_controller.rb, app/views/shared/summary_cards/mini/_network.html.slim, db/migrate/20170913184143_add_resource_type_index_to_resource.rb, db/schema.rb
* resources.resource_type now has an index
* Remove eager loading of users on fetch networks.
* Replaced sample method for get random records by order('RANDOM')
https://github.com/greencommons/commons/issues/269
=> Issue #269 - Improve performance and efficiency of memory allocation on home page request

app/views/static_pages/home.html.slim
=> Issue #262 - Display alerts in home page

app/views/static_pages/_hero.html.slim
=> Change the title of home page
